In [1]:
import numpy as np
a = np.array([1,2,3,4,5],ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [2]:
import numpy as np
a=np.array([1,2,3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [3]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]],dtype = 'float')
print("array created using passed list:\n",a)
b=np.array((1,3,2))
print("array created using passed list:\n",b)
c=np.zeros((3,4))
print("array created using passed list:\n",c)
d=np.full((3,3),6,dtype = 'complex')
print("\nan array initialized with all 6s."
           "array type is complex:\n",d)


array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]
array created using passed list:
 [1 3 2]
array created using passed list:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

an array initialized with all 6s.array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [5]:
e=np.arange(0,40,4)
print("\nan sequential array with steps of 4:\n",e)


an sequential array with steps of 4:
 [ 0  4  8 12 16 20 24 28 32 36]


In [7]:
f=np.random.random((2,2))
print("\nan random array:\n",f)


an random array:
 [[0.88549293 0.65282968]
 [0.34672836 0.04029421]]


In [8]:
g=np.linspace(0,5,10)
print("\na sequential array with 10 values between"
                             "0 and 5:\n",g)


a sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [1]:
import numpy as np
arr = np.array([[1,5,6],
               [4,7,2],
               [3,1,9]])
print("largest element is:",arr.max())
print("row-wise maximum elements:",
                arr.max(axis = 1))
print("column-wise minimum elements:",
        arr.min(axis = 0))
print("sum of all array elements:",
     arr.sum())
print("cummulative sum along each row:\n",
      arr.cumsum(axis = 1))

largest element is: 9
row-wise maximum elements: [6 7 9]
column-wise minimum elements: [1 1 2]
sum of all array elements: 38
cummulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [2]:
from numpy import array
v = array([1,2,3])
print(v)

[1 2 3]


In [3]:
from numpy import array
a=array([1,2,3])
print(a)
b= array([1,2,3])
print(b)
c=a+b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [20]:
class student:
    name = poornima
g=student()
print(g.name)

NameError: name 'poornima' is not defined

In [9]:
import pandas as pd
x=pd.read_csv("C:/Users/wel_home/Desktop/poori/STUDENT DETAILS.csv")
print(x)

    S.NO           NAME  ROLL NO BRANCH  GRADE  CONTACT NO  AGE      ADDRESS
0      1  POORNIMAREDDY      514    CSE     73  7989543040   21  YERRAGUNTLA
1      2        SWARUPA      511    CSE     76  9656402534   20      NELLORE
2      3    RADHA REDDY      424    ECE     80  6300142525   20      NELLORE
3      4         PAVANI      503    CSE     74  7652456810   22      NELLORE
4      5        LAKSHMI      504    CSE     69  9852631472   20    UDAYAGIRI
5      6         JYOTHI      505    CSE     75  9645824327   20    UDAYAGIRI
6      7        SHABANA      506    CSE     80  6321459658   20    UDAYAGIRI
7      8        SHABANA      507    CSE     69  6300025462   20    UDAYAGIRI
8      9       POOJITHA      509    CSE     74  9625483012   22      NELLORE
9     10       SHAILAJA      510    CSE     71  8523647892   20      NELLORE
10     1         GEETHA      515    CSE     72  8500431077   20    PRODDUTUR
11    12        LAVANYA      517    CSE     75  6300452869   20      NELLORE

In [13]:
a,b=[int(x) for x in input("enter 2 numbers:").split()]
print("the sum:",a+b)

enter 2 numbers:10 20
the sum: 30
