# numpy

In [1]:
import numpy as np
lst = [1,2,3,4]
dd = np.array(lst)
dd

array([1, 2, 3, 4])

In [44]:
##ndim gives the dimensions of array
dd.ndim

1

In [50]:
#shape of the array
dd.shape

(4,)

In [51]:
dd.size

4

In [52]:
#creating a two dimentional array
a= [1,23,4,5,6]
b = [2,4,5,6,7]
arr = np.array([a,b])
print(arr)

[[ 1 23  4  5  6]
 [ 2  4  5  6  7]]


In [49]:
arr.ndim

2

In [46]:
arr.shape

(2, 5)

In [19]:
arr.size

10

In [20]:
#array reshaping
arr.reshape(5,2)

array([[ 1, 23],
       [ 4,  5],
       [ 6,  2],
       [ 4,  5],
       [ 6,  7]])

# Slicing & Indexing

In [21]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[5]= 89
arr

array([ 0,  1,  2,  3,  4, 89,  6,  7,  8,  9])

In [26]:
ar1 = [1,2,3,4]
ar2 = [4,6,7,8]
ar3 = [23,4,5,6]
a = np.array([ar1,ar2,ar3])
a


array([[ 1,  2,  3,  4],
       [ 4,  6,  7,  8],
       [23,  4,  5,  6]])

In [29]:
#selecting complete array, all rows and columns a[rows, columns]
a[:,:]

array([[ 1,  2,  3,  4],
       [ 4,  6,  7,  8],
       [23,  4,  5,  6]])

In [34]:
#selecting elements from row1,2 and col 1,2,3
a[1:,1:]

array([[6, 7, 8],
       [4, 5, 6]])

In [35]:
#selecting elements in first 2 rows and first 2 cols
a[:2,:2]

array([[1, 2],
       [4, 6]])

In [63]:
#linspace returns number spaces evenly w.r.t interval.
v = np.linspace(1,10,5)
v

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [66]:
#checking the linspaces
v[2]-v[3]==v[3]-v[4]

True

In [67]:
#copy
a = [1,2,3,4,5,6,7,8]
a

[1, 2, 3, 4, 5, 6, 7, 8]

In [72]:
#copying a values into acopy
acopy = a
acopy

[1, 2, 3, 200, 5, 6, 7, 8]

In [70]:
acopy[3] = 200
acopy

[1, 2, 3, 200, 5, 6, 7, 8]

In [73]:
b = [21,22,23,24,25,26]
b

[21, 22, 23, 24, 25, 26]

In [74]:
bc = b.copy()
bc

[21, 22, 23, 24, 25, 26]

In [78]:
bc[2] = 3000
bc

[21, 22, 3000, 24, 25, 26]

In [82]:
b

[21, 22, 23, 24, 25, 26]

In [84]:
np.zeros(3)

array([0., 0., 0.])

In [86]:
np.ones(2)

array([1., 1.])

In [94]:
c = np.ones((2,2), dtype = int)
print(c)
c.ndim

[[1 1]
 [1 1]]


2

In [96]:
#shows error if you don't mention dtyp for multidimentional array
#Note: Below code displays error and it is done for your reference
np.ones(4,3)

TypeError: data type not understood

In [97]:
#random distribution
np.random.rand(3,3)

array([[0.4416755 , 0.14083018, 0.35390588],
       [0.18222606, 0.71959495, 0.94463369],
       [0.99280217, 0.64323316, 0.22754438]])

In [98]:
#random normal
np.random.randn(4,4)

array([[ 0.45177331,  0.47718152, -1.25080141, -1.58272996],
       [-1.18404865, -0.83204874, -0.4059481 ,  0.95539533],
       [-0.67618318, -1.35212586,  1.60284386, -0.09360863],
       [ 0.57607831,  0.6491205 ,  0.00636746,  1.61944208]])

In [106]:
#random interger
np.random.randint(1,5,8)

array([2, 4, 1, 3, 4, 4, 4, 3])

In [112]:
b =np.random.random_sample((2,3))
b

array([[0.9000002 , 0.2276101 , 0.24075879],
       [0.34653148, 0.64652648, 0.47494527]])